services:
  - type: web
    name: ems-backend
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGODB_URI
        sync: false # Render will prompt you to enter this value during setup
